# Use uma imagem base do PostgreSQL
FROM postgres:latest

# Variáveis de ambiente para configurar o PostgreSQL
ENV POSTGRES_DB=postgres
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=YourStrong!Passw0rd

# Expor a porta padrão do PostgreSQL (5432)
EXPOSE 5432

# Opcional: Copiar arquivos SQL para inicial
